export const waitingList: Record<string, any>[] = [
    {
        Id: 1,
        Subject: 'Weekly Development Meeting',
        StartTime: new Date(2025, 1, 20, 6, 30),
        EndTime: new Date(2025, 1, 20, 7, 30),
        Description: 'Event Scheduled'
    },
    {
        Id: 2,
        Subject: 'Conference meeting',
        StartTime: new Date(2025, 1, 20, 7, 30),
        EndTime: new Date(2025, 1, 20, 8, 30),
        Description: 'Event Scheduled'
    },
    {
        Id: 3,
        Subject: 'Lead Training Session',
        StartTime: new Date(2025, 1, 20, 8, 30),
        EndTime: new Date(2025, 1, 20, 9, 30),
        Description: 'Event Scheduled'
    },
    {
        Id: 4,
        Subject: 'Fresher Training Session',
        StartTime: new Date(2025, 1, 20, 9, 30),
        EndTime: new Date(2025, 1, 20, 10, 30),
        Description: 'Event Scheduled'
    },
];

export const calendarData: Record<string, any>[] = [
    {
        Id: 1,
        Subject: 'Sister-in-law’s Wedding Ceremony',
        StartTime: new Date(2025, 2, 13, 16, 30),
        EndTime: new Date(2025, 2, 14, 10, 30),
        Description: 'Event Scheduled',
        IsAllDay: false,
        IsReadOnly: true,
        CalendarId: 1,
        CategoryId: 1,
        EventType: 'Wedding',
        WeekColor: '#4169E1',
        WorkWeekColor: '#6495ED',
        DayColor: '#00CED1',
        MonthColor: '#20B2AA'
    },
    {
        Id: 2,
        Subject: "Sister-in-law’s Wedding Reception",
        StartTime: new Date(2025, 2, 14, 18, 0),
        EndTime: new Date(2025, 2, 14, 23, 0),
        Description: "Event Scheduled",
        IsAllDay: false,
        IsReadOnly: true,
        CalendarId: 1,
        CategoryId: 1,
        EventType: 'Wedding',
        WeekColor: "#FF69B4",
        WorkWeekColor: "#DB7093",
        DayColor: "#FF1493",
        MonthColor: "#FFB6C1"
    },
    {
        Id: 3,
        Subject: "Grandparents’ Wedding Anniversary",
        StartTime: new Date(2025, 2, 15, 12, 0),
        EndTime: new Date(2025, 2, 15, 15, 0),
        Description: "Event Scheduled",
        IsAllDay: false,
        IsReadOnly: true,
        CalendarId: 1,
        CategoryId: 1,
        EventType: 'Wedding',
        WeekColor: "#FF6347",
        WorkWeekColor: "#CD5C5C",
        DayColor: "#DC143C",
        MonthColor: "#B22222"
    },
    {
        Id: 4,
        Subject: "Parents’ Silver/Golden Anniversary",
        StartTime: new Date(2025, 2, 9, 19, 0),
        EndTime: new Date(2025, 2, 9, 23, 30),
        Description: "Event Scheduled",
        IsAllDay: false,
        IsReadOnly: true,
        CalendarId: 1,
        CategoryId: 1,
        EventType: 'Wedding',
        WeekColor: "#FFD700",
        WorkWeekColor: "#DAA520",
        DayColor: "#FFA500",
        MonthColor: "#F4A460"
    },
    {
        Id: 5,
        Subject: "Cousin’s Engagement",
        StartTime: new Date(2025, 2, 10, 17, 0),
        EndTime: new Date(2025, 2, 10, 21, 0),
        Description: "Event Scheduled",
        IsAllDay: false,
        IsReadOnly: true,
        CalendarId: 1,
        CategoryId: 1,
        EventType: 'Wedding',
        WeekColor: "#FF1493",
        WorkWeekColor: "#FF69B4",
        DayColor: "#DB7093",
        MonthColor: "#FFA07A"
    },
    {
        Id: 6,
        Subject: "Baby Shower",
        StartTime: new Date(2025, 2, 3, 14, 0),
        EndTime: new Date(2025, 2, 3, 16, 0),
        Description: "Event Scheduled",
        IsAllDay: false,
        IsReadOnly: true,
        CalendarId: 1,
        CategoryId: 1,
        EventType: "Baby Shower",
        WeekColor: "#FFB6C1",
        WorkWeekColor: "#FFDAB9",
        DayColor: "#FFA07A",
        MonthColor: "#FA8072"
    },
    {
        Id: 7,
        Subject: "Baby Gender Reveal Party",
        StartTime: new Date(2025, 2, 12, 19, 0),
        EndTime: new Date(2025, 2, 12, 21, 0),
        Description: "Event Scheduled",
        IsAllDay: false,
        IsReadOnly: true,
        CalendarId: 1,
        CategoryId: 1,
        EventType: "Baby Shower",
        WeekColor: "#FFDAB9",
        WorkWeekColor: "#FFA07A",
        DayColor: "#FA8072",
        MonthColor: "#FF69B4"
    },
    {
        Id: 8,
        Subject: "Sibling’s Graduation Ceremony",
        StartTime: new Date(2025, 2, 19, 10, 0),
        EndTime: new Date(2025, 2, 19, 13, 0),
        Description: "Event Scheduled",
        IsAllDay: false,
        IsReadOnly: true,
        CalendarId: 1,
        CategoryId: 1,
        WeekColor: "#F08080",
        WorkWeekColor: "#FF4500",
        DayColor: "#CD5C5C",
        MonthColor: "#FF6347"
    },
    {
        Id: 9,
        Subject: "Housewarming Ceremony",
        StartTime: new Date(2025, 2, 20, 18, 0),
        EndTime: new Date(2025, 2, 20, 22, 0),
        Description: "Event Scheduled",
        IsAllDay: false,
        IsReadOnly: true,
        CalendarId: 1,
        CategoryId: 1,
        EventType: "Housewarming",
        WeekColor: "#FF7F50",
        WorkWeekColor: "#FFA500",
        DayColor: "#CD853F",
        MonthColor: "#D2691E"
    },
    {
        Id: 10,
        Subject: "Moving to a New House",
        StartTime: new Date(2025, 2, 21, 9, 0),
        EndTime: new Date(2025, 2, 21, 18, 0),
        Description: "Event Scheduled",
        IsAllDay: true,
        IsReadOnly: true,
        CalendarId: 1,
        CategoryId: 1,
        EventType: "Housewarming",
        WeekColor: "#FA8072",
        WorkWeekColor: "#FFA07A",
        DayColor: "#FF6347",
        MonthColor: "#CD5C5C"
    },
    {
        Id: 11,
        Subject: "New Car Delivery Ceremony",
        StartTime: new Date(2025, 2, 22, 11, 0),
        EndTime: new Date(2025, 2, 22, 14, 0),
        Description: "Event Scheduled",
        IsAllDay: false,
        IsReadOnly: true,
        CalendarId: 1,
        CategoryId: 1,
        EventType: "New Car Delivery",
        WeekColor: "#FF4500",
        WorkWeekColor: "#DC143C",
        DayColor: "#B22222",
        MonthColor: "#A52A2A"
    },

    {
        Id: 12,
        Subject: "Engagement Day",
        StartTime: new Date(2025, 2, 9, 18, 0),
        EndTime: new Date(2025, 2, 9, 22, 0),
        Description: "Celebrating our engagement",
        IsAllDay: true,
        IsReadOnly: true,
        CalendarId: 1,
        CategoryId: 2,
        EventType: 'Wedding',
        WeekColor: "#FF69B4",
        WorkWeekColor: "#DB7093",
        DayColor: "#FF1493",
        MonthColor: "#FFC0CB"
    },
    {
        Id: 13,
        Subject: "Wedding Anniversary",
        StartTime: new Date(2025, 2, 5, 19, 0),
        EndTime: new Date(2025, 2, 5, 23, 0),
        Description: "Special day to celebrate love",
        IsAllDay: true,
        IsReadOnly: true,
        CalendarId: 1,  
        CategoryId: 2,
        EventType: "Wedding",
        WeekColor: "#FFD700",
        WorkWeekColor: "#DAA520",
        DayColor: "#FFA500",
        MonthColor: "#F4A460"
    },
    {
        Id: 14,
        Subject: "Medical Check-up",
        StartTime: new Date(2025, 3, 3, 10, 0),
        EndTime: new Date(2025, 3, 3, 11, 30),
        Description: "Routine health check-up",
        IsAllDay: false,
        IsReadOnly: true,
        CalendarId: 1,
        CategoryId: 2,
        EventType: "Medical Check-up",
        WeekColor: "#32CD32",
        WorkWeekColor: "#008000",
        DayColor: "#2E8B57",
        MonthColor: "#66CDAA"
    },
    {
        Id: 15,
        Subject: "Fitness Challenge Start",
        StartTime: new Date(2025, 2, 6, 6, 0),
        EndTime: new Date(2025, 2, 6, 7, 0),
        Description: "Starting a new fitness journey",
        IsAllDay: false,
        IsReadOnly: true,
        CalendarId: 1,
        CategoryId: 2,
        EventType: "Fitness",
        WeekColor: "#00CED1",
        WorkWeekColor: "#20B2AA",
        DayColor: "#40E0D0",
        MonthColor: "#5F9EA0"
    },
    {
        Id: 16,
        Subject: "Fitness Challenge End",
        StartTime: new Date(2025, 3, 13, 6, 0),
        EndTime: new Date(2025, 3, 13, 7, 0),
        Description: "Challenge completion day",
        IsAllDay: false,
        IsReadOnly: true,
        CalendarId: 1,
        CategoryId: 2,
        EventType: "Fitness",
        WeekColor: "#00CED1",
        WorkWeekColor: "#20B2AA",
        DayColor: "#40E0D0",
        MonthColor: "#5F9EA0"
    },
    {
        Id: 17,
        Subject: "Yoga Retreat",
        StartTime: new Date(2025, 2, 14, 8, 0),
        EndTime: new Date(2025, 2, 14, 18, 0),
        Description: "Relax and rejuvenate",
        IsAllDay: true,
        IsReadOnly: true,
        CalendarId: 1,
        CategoryId: 2,
        EventType: "Yoga",
        WeekColor: "#4682B4",
        WorkWeekColor: "#1E90FF",
        DayColor: "#4169E1",
        MonthColor: "#87CEFA"
    },

    {
        Id: 18,
        Subject: "Family Vacation Trip",
        StartTime: new Date(2025, 2, 29, 8, 0),
        EndTime: new Date(2025, 2, 31, 20, 0),
        Description: "A relaxing vacation with family",
        IsAllDay: true,
        IsReadOnly: true,
        CalendarId: 1,
        CategoryId: 3,
        EventType: "Vacation",
        WeekColor: "#FF8C00",
        WorkWeekColor: "#FFA500",
        DayColor: "#FF4500",
        MonthColor: "#7B1FA2"
    },
    {
        Id: 19,
        Subject: "Family Get-together",
        StartTime: new Date(2025, 2, 9, 16, 0),
        EndTime: new Date(2025, 2, 9, 21, 0),
        Description: "Catching up with loved ones",
        IsAllDay: false,
        IsReadOnly: true,
        CalendarId: 1,
        CategoryId: 3,
        EventType: "Weekend Celebration",
        WeekColor: "#DAA520",
        WorkWeekColor: "#FFD700",
        DayColor: "#F4A460",
        MonthColor: "#D2691E"
    },
    {
        Id: 20,
        Subject: "College Reunion",
        StartTime: new Date(2025, 2, 15, 18, 0),
        EndTime: new Date(2025, 2, 15, 23, 59),
        Description: "Reuniting with old friends",
        IsAllDay: false,
        IsReadOnly: true,
        CalendarId: 1,
        CategoryId: 3,
        EventType: "Weekend Celebration",
        WeekColor: "#8A2BE2",
        WorkWeekColor: "#6A5ACD",
        DayColor: "#7B68EE",
        MonthColor: "#9370DB"
    },
    {
        Id: 21,
        Subject: "Weekend Getaway",
        StartTime: new Date(2025, 2, 15, 6, 0),
        EndTime: new Date(2025, 2, 16, 22, 0),
        Description: "Short refreshing break",
        IsAllDay: true,
        IsReadOnly: true,
        CalendarId: 1,
        CategoryId: 3,
        EventType: "Weekend Celebration",
        WeekColor: "#20B2AA",
        WorkWeekColor: "#5F9EA0",
        DayColor: "#008B8B",
        MonthColor: "#7B1FA2"
    },

    // Appointments & Maintenance
    {
        Id: 22,
        Subject: "Bike Service Appointment",
        StartTime: new Date(2025, 2, 10, 9, 0),
        EndTime: new Date(2025, 2, 10, 11, 0),
        Description: "Routine bike service check-up",
        IsAllDay: false,
        IsReadOnly: true,
        CalendarId: 1,
        CategoryId: 4,
        EventType: "Service",
        WeekColor: "#2E8B57",
        WorkWeekColor: "#228B22",
        DayColor: "#008000",
        MonthColor: "#6B8E23"
    },
    {
        Id: 23,
        Subject: "Charity Event Participation",
        StartTime: new Date(2025, 2, 7, 14, 0),
        EndTime: new Date(2025, 2, 7, 18, 0),
        Description: "Giving back to the community",
        IsAllDay: false,
        IsReadOnly: true,
        CalendarId: 1,
        CategoryId: 4,
        EventType: "Charity",
        WeekColor: "#FF4500",
        WorkWeekColor: "#DC143C",
        DayColor: "#B22222",
        MonthColor: "#8B0000"
    },

    // Special Celebrations & Remembrances
    {
        Id: 24,
        Subject: "Revanth’s Wedding Anniversary",
        StartTime: new Date(2025, 2, 6, 18, 0),
        EndTime: new Date(2025, 2, 6, 23, 0),
        Description: "Celebrating Revanth’s special day",
        IsAllDay: false,
        IsReadOnly: true,
        CalendarId: 1,
        CategoryId: 5,
        EventType: "Wedding",
        WeekColor: "#FFD700",
        WorkWeekColor: "#DAA520",
        DayColor: "#FFA500",
        MonthColor: "#F4A460"
    },
    {
        Id: 25,
        Subject: "Rahul’s Wedding Anniversary",
        StartTime: new Date(2025, 2, 15, 19, 0),
        EndTime: new Date(2025, 2, 15, 23, 59),
        Description: "Honoring Rahul’s wedding anniversary",
        IsAllDay: false,
        IsReadOnly: true,
        CalendarId: 1,
        CategoryId: 5,
        EventType: "Wedding",
        WeekColor: "#8A2BE2",
        WorkWeekColor: "#6A5ACD",
        DayColor: "#7B68EE",
        MonthColor: "#9370DB"
    },

    // Team & Project Management
    {
        Id: 26,
        Subject: "Team Scrum Meeting",
        StartTime: new Date(2025, 2, 10, 9, 30),
        EndTime: new Date(2025, 2, 10, 10, 0),
        Description: "Daily stand-up to discuss progress",
        RecurrenceRule: 'FREQ=WEEKLY;BYDAY=MO,TU,WE,TH,FR;INTERVAL=1;COUNT=10;',
        IsAllDay: false,
        IsReadOnly: true,
        CalendarId: 2,
        CategoryId: 6,
        EventType: "Group Meeting",
        WeekColor: "#1E90FF",
        WorkWeekColor: "#4682B4",
        DayColor: "#4169E1",
        MonthColor: "#f0f8ff",
        MonthFontColor: "#333"
    },
    {
        Id: 27,
        Subject: "Sprint Planning Meeting",
        StartTime: new Date(2025, 2, 11, 14, 0),
        EndTime: new Date(2025, 2, 11, 16, 0),
        Description: "Planning tasks for the upcoming sprint",
        IsAllDay: false,
        IsReadOnly: true,
        CalendarId: 2,
        CategoryId: 6,
        EventType: "Group Meeting",
        WeekColor: "#FFA500",
        WorkWeekColor: "#FF8C00",
        DayColor: "#FF4500",
        MonthColor: "#FFD700"
    },
    {
        Id: 28,
        Subject: "Sprint Retrospective Meeting",
        StartTime: new Date(2025, 2, 14, 16, 0),
        EndTime: new Date(2025, 2, 14, 17, 0),
        Description: "Reviewing sprint performance and improvements",
        IsAllDay: false,
        IsReadOnly: true,
        CalendarId: 2,
        CategoryId: 6,
        EventType: "Group Meeting",
        WeekColor: "#32CD32",
        WorkWeekColor: "#228B22",
        DayColor: "#008000",
        MonthColor: "#6B8E23"
    },
    {
        Id: 29,
        Subject: "Bug Triage Meeting",
        StartTime: new Date(2025, 2, 20, 15, 0),
        EndTime: new Date(2025, 2, 20, 16, 30),
        Description: "Prioritizing and resolving reported bugs",
        IsAllDay: false,
        IsReadOnly: true,
        CalendarId: 2,
        CategoryId: 6,
        EventType: "Group Meeting",
        WeekColor: "#FF6347",
        WorkWeekColor: "#DC143C",
        DayColor: "#B22222",
        MonthColor: "#8B0000"
    },
    {
        Id: 30,
        Subject: "Cross-Team Collaboration Meeting",
        StartTime: new Date(2025, 2, 21, 11, 0),
        EndTime: new Date(2025, 2, 21, 12, 30),
        Description: "Sync between different departments",
        IsAllDay: false,
        IsReadOnly: true,
        CalendarId: 2,
        CategoryId: 6,
        EventType: "Group Meeting",
        WeekColor: "#8A2BE2",
        WorkWeekColor: "#6A5ACD",
        DayColor: "#7B68EE",
        MonthColor: "#9370DB"
    },
    {
        Id: 31,
        Subject: "Weekly Development Meeting",
        StartTime: new Date(2025, 3, 22, 10, 0),
        EndTime: new Date(2025, 3, 22, 11, 0),
        Description: "Discussing weekly development updates",
        IsAllDay: false,
        IsReadOnly: true,
        CalendarId: 2,
        CategoryId: 6,
        EventType: "Group Meeting",
        WeekColor: "#20B2AA",
        WorkWeekColor: "#5F9EA0",
        DayColor: "#008B8B",
        MonthColor: "#66CDAA"
    },
    {
        Id: 32,
        Subject: "Project Review",
        StartTime: new Date(2025, 2, 24, 15, 0),
        EndTime: new Date(2025, 2, 24, 16, 30),
        Description: "Reviewing project progress and next steps",
        IsAllDay: false,
        IsReadOnly: true,
        CalendarId: 2,
        CategoryId: 6,
        EventType: "Business meeting",
        WeekColor: "#FF1493",
        WorkWeekColor: "#DB7093",
        DayColor: "#FF69B4",
        MonthColor: "#FFC0CB"
    },
    {
        Id: 33,
        Subject: "Demo Meeting",
        StartTime: new Date(2025, 3, 24, 14, 0),
        EndTime: new Date(2025, 3, 24, 15, 30),
        Description: "Demonstrating new features and updates",
        IsAllDay: false,
        IsReadOnly: true,
        CalendarId: 2,
        CategoryId: 6,
        EventType: "Product Innovation",
        WeekColor: "#4682B4",
        WorkWeekColor: "#1E90FF",
        DayColor: "#4169E1",
        MonthColor: "#87CEFA"
    },

    // Business & Strategy

    {
        Id: 34,
        Subject: "Quarterly Business Review",
        StartTime: new Date(2025, 2, 10, 10, 0),
        EndTime: new Date(2025, 2, 10, 12, 0),
        Description: "Reviewing the company's quarterly performance",
        IsAllDay: false,
        IsReadOnly: true,
        CalendarId: 2,
        CategoryId: 7,
        EventType: "Business meeting",
        WeekColor: "#4169E1",
        WorkWeekColor: "#1E90FF",
        DayColor: "#4682B4",
        MonthColor: "#87CEFA"
    },
    {
        Id: 35,
        Subject: "Market Analysis & Competitor Review",
        StartTime: new Date(2025, 2, 11, 14, 0),
        EndTime: new Date(2025, 2, 11, 16, 0),
        Description: "Evaluating market trends and competitors",
        IsAllDay: false,
        IsReadOnly: true,
        CalendarId: 2,
        CategoryId: 7,
        EventType: "Business meeting",
        WeekColor: "#32CD32",
        WorkWeekColor: "#228B22",
        DayColor: "#008000",
        MonthColor: "#6B8E23"
    },
    {
        Id: 36,
        Subject: "Company Growth Discussion",
        StartTime: new Date(2025, 2, 12, 11, 0),
        EndTime: new Date(2025, 2, 12, 12, 30),
        Description: "Discussing company expansion and scaling",
        IsAllDay: false,
        IsReadOnly: true,
        CalendarId: 2,
        CategoryId: 7,
        EventType: "Business meeting",
        WeekColor: "#FF8C00",
        WorkWeekColor: "#FFA500",
        DayColor: "#FF4500",
        MonthColor: "#FFD700"
    },
    {
        Id: 37,
        Subject: "Risk Management Discussion",
        StartTime: new Date(2025, 2, 13, 15, 0),
        EndTime: new Date(2025, 2, 13, 16, 30),
        Description: "Identifying and mitigating business risks",
        IsAllDay: false,
        IsReadOnly: true,
        CalendarId: 2,
        CategoryId: 7,
        EventType: "Business meeting",
        WeekColor: "#DC143C",
        WorkWeekColor: "#B22222",
        DayColor: "#8B0000",
        MonthColor: "#FF6347"
    },
    {
        Id: 38,
        Subject: "Crisis Management Meeting",
        StartTime: new Date(2025, 2, 14, 10, 30),
        EndTime: new Date(2025, 2, 14, 12, 0),
        Description: "Preparing strategies for crisis response",
        IsAllDay: false,
        IsReadOnly: true,
        CalendarId: 2,
        CategoryId: 7,
        EventType: "Business meeting",
        WeekColor: "#8A2BE2",
        WorkWeekColor: "#6A5ACD",
        DayColor: "#7B68EE",
        MonthColor: "#9370DB"
    },
    {
        Id: 39,
        Subject: "Pricing Strategy Discussion",
        StartTime: new Date(2025, 2, 17, 14, 0),
        EndTime: new Date(2025, 2, 17, 16, 0),
        Description: "Determining product/service pricing",
        IsAllDay: false,
        IsReadOnly: true,
        CalendarId: 2,
        CategoryId: 7,
        EventType: "Business meeting",
        WeekColor: "#20B2AA",
        WorkWeekColor: "#5F9EA0",
        DayColor: "#008B8B",
        MonthColor: "#66CDAA"
    },
    {
        Id: 40,
        Subject: "Annual Budget Planning",
        StartTime: new Date(2025, 2, 18, 10, 0),
        EndTime: new Date(2025, 2, 18, 13, 0),
        Description: "Allocating resources and setting budgets",
        IsAllDay: false,
        IsReadOnly: true,
        CalendarId: 2,
        CategoryId: 7,
        EventType: "Business meeting",
        WeekColor: "#FFD700",
        WorkWeekColor: "#DAA520",
        DayColor: "#FFA500",
        MonthColor: "#F4A460"
    },

    // Performance & HR

    {
        Id: 41,
        Subject: "Onboarding Session",
        StartTime: new Date(2025, 2, 10, 9, 0),
        EndTime: new Date(2025, 2, 10, 11, 0),
        Description: "Welcoming new hires and introducing company culture",
        IsAllDay: false,
        IsReadOnly: true,
        CalendarId: 2,
        CategoryId: 8,
        EventType: "Leadership Development",
        WeekColor: "#FF4500",
        WorkWeekColor: "#FF6347",
        DayColor: "#FF7F50",
        MonthColor: "#FFA07A"
    },
    {
        Id: 42,
        Subject: "Diversity & Inclusion Training",
        StartTime: new Date(2025, 2, 11, 14, 0),
        EndTime: new Date(2025, 2, 11, 16, 0),
        Description: "Promoting workplace diversity and inclusivity",
        IsAllDay: false,
        IsReadOnly: true,
        CalendarId: 2,
        CategoryId: 8,
        EventType: "Leadership Development",
        WeekColor: "#008080",
        WorkWeekColor: "#20B2AA",
        DayColor: "#5F9EA0",
        MonthColor: "#66CDAA"
    },
    {
        Id: 43,
        Subject: "Work Anniversary Celebration",
        StartTime: new Date(2025, 2, 12, 12, 0),
        EndTime: new Date(2025, 2, 12, 13, 30),
        Description: "Celebrating employees' work anniversaries",
        IsAllDay: false,
        IsReadOnly: true,
        CalendarId: 2,
        CategoryId: 8,
        EventType: "Performance",
        WeekColor: "#FFD700",
        WorkWeekColor: "#DAA520",
        DayColor: "#FFA500",
        MonthColor: "#F4A460"
    },
    {
        Id: 44,
        Subject: "Hike Discussion",
        StartTime: new Date(2025, 2, 13, 10, 0),
        EndTime: new Date(2025, 2, 13, 11, 30),
        Description: "Discussing salary hikes and promotions",
        IsAllDay: false,
        IsReadOnly: true,
        CalendarId: 2,
        CategoryId: 8,
        EventType: "Performance",
        WeekColor: "#8B0000",
        WorkWeekColor: "#B22222",
        DayColor: "#DC143C",
        MonthColor: "#FF6347"
    },
    {
        Id: 45,
        Subject: "Monthly Performance Review",
        StartTime: new Date(2025, 2, 28, 15, 0),
        EndTime: new Date(2025, 2, 28, 17, 0),
        Description: "Reviewing team and individual performance",
        IsAllDay: false,
        IsReadOnly: true,
        CalendarId: 2,
        CategoryId: 8,
        EventType: "Performance",
        WeekColor: "#4169E1",
        WorkWeekColor: "#1E90FF",
        DayColor: "#4682B4",
        MonthColor: "#87CEFA"
    },
    {
        Id: 46,
        Subject: "Performance Improvement Plan Review",
        StartTime: new Date(2025, 2, 17, 14, 0),
        EndTime: new Date(2025, 2, 17, 15, 30),
        Description: "Evaluating progress of improvement plans",
        IsAllDay: false,
        IsReadOnly: true,
        CalendarId: 2,
        CategoryId: 8,
        EventType: "Performance",
        WeekColor: "#32CD32",
        WorkWeekColor: "#228B22",
        DayColor: "#008000",
        MonthColor: "#6B8E23"
    },
    {
        Id: 47,
        Subject: "High-Performer Recognition Event",
        StartTime: new Date(2025, 2, 18, 18, 0),
        EndTime: new Date(2025, 2, 18, 20, 0),
        Description: "Recognizing and rewarding top performers",
        IsAllDay: false,
        IsReadOnly: true,
        CalendarId: 2,
        CategoryId: 8,
        EventType: "Performance",
        WeekColor: "#9400D3",
        WorkWeekColor: "#8A2BE2",
        DayColor: "#7B68EE",
        MonthColor: "#9370DB"
    },
    {
        Id: 48,
        Subject: "Workforce Planning & Talent Acquisition Meeting",
        StartTime: new Date(2025, 2, 19, 10, 0),
        EndTime: new Date(2025, 2, 19, 12, 0),
        Description: "Discussing hiring plans and workforce needs",
        IsAllDay: false,
        IsReadOnly: true,
        CalendarId: 2,
        CategoryId: 8,
        EventType: "Leadership Development",
        WeekColor: "#4682B4",
        WorkWeekColor: "#5F9EA0",
        DayColor: "#20B2AA",
        MonthColor: "#00CED1"
    },
    {
        Id: 49,
        Subject: "Succession Planning Discussion",
        StartTime: new Date(2025, 2, 20, 11, 0),
        EndTime: new Date(2025, 2, 20, 12, 30),
        Description: "Planning leadership succession and growth",
        IsAllDay: false,
        IsReadOnly: true,
        CalendarId: 2,
        CategoryId: 8,
        EventType: "Leadership Development",
        WeekColor: "#FF8C00",
        WorkWeekColor: "#FFA500",
        DayColor: "#FF4500",
        MonthColor: "#FFD700"
    },

    // Leadership & Development

    {
        Id: 50,
        Subject: "Quarterly Leadership Summit",
        StartTime: new Date(2025, 2, 12, 9, 0),
        EndTime: new Date(2025, 2, 12, 12, 0),
        Description: "Discussing leadership strategies and organizational vision",
        IsAllDay: false,
        IsReadOnly: true,
        CalendarId: 2,
        CategoryId: 9,
        EventType: "Leadership Development",
        WeekColor: "#8B008B",
        WorkWeekColor: "#9400D3",
        DayColor: "#9932CC",
        MonthColor: "#BA55D3"
    },
    {
        Id: 51,
        Subject: "Soft Skills Development Workshop",
        StartTime: new Date(2025, 2, 13, 14, 0),
        EndTime: new Date(2025, 2, 13, 16, 0),
        Description: "Enhancing communication, teamwork, and problem-solving skills",
        IsAllDay: false,
        IsReadOnly: true,
        CalendarId: 2,
        CategoryId: 9,
        EventType: "Leadership Development",
        WeekColor: "#2E8B57",
        WorkWeekColor: "#3CB371",
        DayColor: "#20B2AA",
        MonthColor: "#66CDAA"
    },
    {
        Id: 52,
        Subject: "Managerial Coaching & Mentorship Program",
        StartTime: new Date(2025, 2, 14, 10, 0),
        EndTime: new Date(2025, 2, 14, 12, 0),
        Description: "Providing guidance for managers to enhance leadership skills",
        IsAllDay: false,
        IsReadOnly: true,
        CalendarId: 2,
        CategoryId: 9,
        EventType: "Leadership Development",
        WeekColor: "#FF4500",
        WorkWeekColor: "#FF6347",
        DayColor: "#FF7F50",
        MonthColor: "#FFA07A"
    },
    {
        Id: 53,
        Subject: "Leadership Training Session",
        StartTime: new Date(2025, 2, 17, 9, 30),
        EndTime: new Date(2025, 2, 17, 11, 30),
        Description: "Training on leadership effectiveness and decision-making",
        IsAllDay: false,
        IsReadOnly: true,
        CalendarId: 2,
        CategoryId: 9,
        EventType: "Leadership Development",
        WeekColor: "#1E90FF",
        WorkWeekColor: "#4169E1",
        DayColor: "#4682B4",
        MonthColor: "#87CEFA"
    },
    {
        Id: 54,
        Subject: "Policy & Compliance Update Meeting",
        StartTime: new Date(2025, 2, 18, 11, 0),
        EndTime: new Date(2025, 2, 18, 12, 30),
        Description: "Reviewing corporate policies and compliance updates",
        IsAllDay: false,
        IsReadOnly: true,
        CalendarId: 2,
        CategoryId: 9,
        EventType: "Business meeting",
        WeekColor: "#8B0000",
        WorkWeekColor: "#B22222",
        DayColor: "#DC143C",
        MonthColor: "#FF6347"
    },

    // Sales & Customer Relations

    {
        Id: 55,
        Subject: "Customer Meeting",
        StartTime: new Date(2025, 2, 23, 10, 0),
        EndTime: new Date(2025, 2, 23, 11, 30),
        Description: "Discussing business opportunities and customer requirements",
        IsAllDay: false,
        IsReadOnly: true,
        CalendarId: 2,
        CategoryId: 10,
        EventType: "One One meeting",
        WeekColor: "#008B8B",
        WorkWeekColor: "#20B2AA",
        DayColor: "#5F9EA0",
        MonthColor: "#48D1CC"
    },
    {
        Id: 56,
        Subject: "Customer Feedback Analysis",
        StartTime: new Date(2025, 2, 11, 14, 0),
        EndTime: new Date(2025, 2, 11, 15, 30),
        Description: "Reviewing customer feedback to improve service and products",
        IsAllDay: false,
        IsReadOnly: true,
        CalendarId: 2,
        CategoryId: 10,
        EventType: "Customer Relations",
        WeekColor: "#FF8C00",
        WorkWeekColor: "#FFA500",
        DayColor: "#FFD700",
        MonthColor: "#FFA07A"
    },
    {
        Id: 57,
        Subject: "Sales Target Discussion",
        StartTime: new Date(2025, 2, 12, 9, 30),
        EndTime: new Date(2025, 2, 12, 11, 0),
        Description: "Strategizing to achieve sales targets for the next quarter",
        IsAllDay: false,
        IsReadOnly: true,
        CalendarId: 2,
        CategoryId: 10,
        EventType: "Business meeting",
        WeekColor: "#32CD32",
        WorkWeekColor: "#228B22",
        DayColor: "#008000",
        MonthColor: "#7FFF00"
    },
    {
        Id: 58,
        Subject: "Sales Funnel Review",
        StartTime: new Date(2025, 2, 27, 10, 0),
        EndTime: new Date(2025, 2, 27, 11, 30),
        Description: "Assessing lead conversion and sales funnel optimization",
        IsAllDay: false,
        IsReadOnly: true,
        CalendarId: 2,
        CategoryId: 10,
        EventType: "Customer Relations",
        WeekColor: "#4682B4",
        WorkWeekColor: "#1E90FF",
        DayColor: "#00BFFF",
        MonthColor: "#87CEFA"
    },
    {
        Id: 59,
        Subject: "Vendor & Partner Negotiation Meeting",
        StartTime: new Date(2025, 2, 14, 14, 0),
        EndTime: new Date(2025, 2, 14, 15, 30),
        Description: "Negotiating terms and agreements with vendors and partners",
        IsAllDay: false,
        IsReadOnly: true,
        CalendarId: 2,
        CategoryId: 10,
        EventType: "Business meeting",
        WeekColor: "#8B4513",
        WorkWeekColor: "#A0522D",
        DayColor: "#D2691E",
        MonthColor: "#CD853F"
    },
    {
        Id: 60,
        Subject: "Client Appreciation Dinner",
        StartTime: new Date(2025, 2, 17, 19, 0),
        EndTime: new Date(2025, 2, 17, 21, 0),
        Description: "A networking dinner to show appreciation to key clients",
        IsAllDay: false,
        IsReadOnly: true,
        CalendarId: 2,
        CategoryId: 10,
        EventType: "Customer Relations",
        WeekColor: "#B22222",
        WorkWeekColor: "#DC143C",
        DayColor: "#FF4500",
        MonthColor: "#FF6347"
    },
    {
        Id: 61,
        Subject: "Contract Renewal Discussion",
        StartTime: new Date(2025, 2, 18, 10, 0),
        EndTime: new Date(2025, 2, 18, 11, 30),
        Description: "Discussing terms and renewal of existing contracts",
        IsAllDay: false,
        IsReadOnly: true,
        CalendarId: 2,
        CategoryId: 10,
        EventType: "Business meeting",
        WeekColor: "#4B0082",
        WorkWeekColor: "#6A5ACD",
        DayColor: "#8A2BE2",
        MonthColor: "#9370DB"
    },

    // Product & Innovation

    {
        Id: 62,
        Subject: "Product Roadmap Discussion",
        StartTime: new Date(2025, 2, 26, 10, 0),
        EndTime: new Date(2025, 2, 26, 11, 30),
        Description: "Defining product strategy and feature rollout timeline",
        IsAllDay: false,
        IsReadOnly: true,
        CalendarId: 2,
        CategoryId: 11,
        EventType: "Product Innovation",
        WeekColor: "#2E8B57",
        WorkWeekColor: "#3CB371",
        DayColor: "#20B2AA",
        MonthColor: "#66CDAA"
    },
    {
        Id: 63,
        Subject: "Beta Testing Review",
        StartTime: new Date(2025, 2, 11, 14, 0),
        EndTime: new Date(2025, 2, 11, 15, 30),
        Description: "Analyzing user feedback from beta testing phase",
        IsAllDay: false,
        IsReadOnly: true,
        CalendarId: 2,
        CategoryId: 11,
        EventType: "Product Innovation",
        WeekColor: "#FF8C00",
        WorkWeekColor: "#FFA500",
        DayColor: "#FFD700",
        MonthColor: "#FFA07A"
    },
    {
        Id: 64,
        Subject: "User Experience (UX) Research Meeting",
        StartTime: new Date(2025, 2, 12, 10, 0),
        EndTime: new Date(2025, 2, 12, 11, 30),
        Description: "Improving UX based on customer feedback and usability tests",
        IsAllDay: false,
        IsReadOnly: true,
        CalendarId: 2,
        CategoryId: 11,
        EventType: "Product Innovation",
        WeekColor: "#4682B4",
        WorkWeekColor: "#1E90FF",
        DayColor: "#00BFFF",
        MonthColor: "#87CEFA"
    },
    {
        Id: 65,
        Subject: "New Launch Discussion",
        StartTime: new Date(2025, 2, 13, 14, 0),
        EndTime: new Date(2025, 2, 13, 15, 30),
        Description: "Planning strategies for upcoming product launch",
        IsAllDay: false,
        IsReadOnly: true,
        CalendarId: 2,
        CategoryId: 11,
        EventType: "Product Innovation",
        WeekColor: "#8B4513",
        WorkWeekColor: "#A0522D",
        DayColor: "#D2691E",
        MonthColor: "#CD853F"
    },
    {
        Id: 66,
        Subject: "Hackathon Event",
        StartTime: new Date(2025, 2, 14, 9, 0),
        EndTime: new Date(2025, 2, 14, 18, 0),
        Description: "Innovation event for teams to build and pitch new ideas",
        IsAllDay: false,
        IsReadOnly: true,
        CalendarId: 2,
        CategoryId: 11,
        EventType: "Product Innovation",
        WeekColor: "#B22222",
        WorkWeekColor: "#DC143C",
        DayColor: "#FF4500",
        MonthColor: "#FF6347"
    },

    // Security & Compliance

    {
        Id: 67,
        Subject: "Cybersecurity Awareness Session",
        StartTime: new Date(2025, 2, 25, 10, 0),
        EndTime: new Date(2025, 2, 25, 11, 30),
        Description: "Training on best practices to enhance cybersecurity awareness",
        IsAllDay: false,
        IsReadOnly: true,
        CalendarId: 2,
        CategoryId: 12,
        EventType: "Cybersecurity",
        WeekColor: "#800000",
        WorkWeekColor: "#A52A2A",
        DayColor: "#B22222",
        MonthColor: "#CD5C5C"
    },
    {
        Id: 68,
        Subject: "Crisis Management Meeting",
        StartTime: new Date(2025, 2, 11, 14, 0),
        EndTime: new Date(2025, 2, 11, 15, 30),
        Description: "Developing strategies to respond to security incidents effectively",
        IsAllDay: false,
        IsReadOnly: true,
        CalendarId: 2,
        CategoryId: 12,
        EventType: "Cybersecurity",
        WeekColor: "#2F4F4F",
        WorkWeekColor: "#556B2F",
        DayColor: "#6B8E23",
        MonthColor: "#8FBC8F"
    },
    {
        Id: 69,
        Subject: "IT Infrastructure Audit",
        StartTime: new Date(2025, 2, 12, 10, 0),
        EndTime: new Date(2025, 2, 12, 11, 30),
        Description: "Reviewing and assessing IT infrastructure for security gaps",
        IsAllDay: false,
        IsReadOnly: true,
        CalendarId: 2,
        CategoryId: 12,
        EventType: "Cybersecurity",
        WeekColor: "#4682B4",
        WorkWeekColor: "#1E90FF",
        DayColor: "#00BFFF",
        MonthColor: "#87CEFA"
    },
    {
        Id: 70,
        Subject: "Compliance Certification Review",
        StartTime: new Date(2025, 2, 13, 14, 0),
        EndTime: new Date(2025, 2, 13, 15, 30),
        Description: "Ensuring company meets all security and compliance standards",
        IsAllDay: false,
        IsReadOnly: true,
        CalendarId: 2,
        CategoryId: 12,
        EventType: "Cybersecurity",
        WeekColor: "#8B4513",
        WorkWeekColor: "#A0522D",
        DayColor: "#D2691E",
        MonthColor: "#CD853F"
    },
    {
        Id: 71,
        Subject: "Data Privacy & GDPR Compliance Review",
        StartTime: new Date(2025, 2, 14, 10, 0),
        EndTime: new Date(2025, 2, 14, 11, 30),
        Description: "Assessing adherence to data privacy regulations and GDPR compliance",
        IsAllDay: false,
        IsReadOnly: true,
        CalendarId: 2,
        CategoryId: 12,
        EventType: "Cybersecurity",
        WeekColor: "#4B0082",
        WorkWeekColor: "#6A5ACD",
        DayColor: "#8A2BE2",
        MonthColor: "#9370DB"
    },

    // Company Culture & Engagement

    {
        Id: 72,
        Subject: "Internal Knowledge Sharing Session",
        StartTime: new Date(2025, 2, 10, 10, 0),
        EndTime: new Date(2025, 2, 10, 11, 30),
        Description: "Employees sharing expertise and industry insights",
        IsAllDay: false,
        IsReadOnly: true,
        CalendarId: 2,
        CategoryId: 13,
        EventType: "Group Meeting",
        WeekColor: "#4682B4",
        WorkWeekColor: "#1E90FF",
        DayColor: "#00BFFF",
        MonthColor: "#87CEEB"
    },
    {
        Id: 73,
        Subject: "Employee Wellness Webinar",
        StartTime: new Date(2025, 2, 11, 14, 0),
        EndTime: new Date(2025, 2, 11, 15, 30),
        Description: "Health and wellness session for employees",
        IsAllDay: false,
        IsReadOnly: true,
        CalendarId: 2,
        CategoryId: 13,
        EventType: "Performance",
        WeekColor: "#32CD32",
        WorkWeekColor: "#3CB371",
        DayColor: "#2E8B57",
        MonthColor: "#66CDAA"
    },
    {
        Id: 74,
        Subject: "Charity & Social Responsibility Event",
        StartTime: new Date(2025, 2, 12, 10, 0),
        EndTime: new Date(2025, 2, 12, 12, 30),
        Description: "Company-driven community and charity initiatives",
        IsAllDay: false,
        IsReadOnly: true,
        CalendarId: 2,
        CategoryId: 13,
        EventType: "Group Meeting",
        WeekColor: "#FF8C00",
        WorkWeekColor: "#FFA500",
        DayColor: "#FFD700",
        MonthColor: "#FFA07A"
    },
    {
        Id: 75,
        Subject: "Team Building Outdoor Activity",
        StartTime: new Date(2025, 2, 13, 9, 0),
        EndTime: new Date(2025, 2, 13, 17, 0),
        Description: "Outdoor activities for team bonding and collaboration",
        IsAllDay: false,
        IsReadOnly: true,
        CalendarId: 2,
        CategoryId: 13,
        EventType: "Group Meeting",
        WeekColor: "#8B4513",
        WorkWeekColor: "#A0522D",
        DayColor: "#D2691E",
        MonthColor: "#CD853F"
    },
    {
        Id: 76,
        Subject: "Annual General Meeting",
        StartTime: new Date(2025, 2, 14, 10, 0),
        EndTime: new Date(2025, 2, 14, 12, 30),
        Description: "Yearly meeting to review company progress and future plans",
        IsAllDay: false,
        IsReadOnly: true,
        CalendarId: 2,
        CategoryId: 13,
        EventType: "Group Meeting",
        WeekColor: "#800000",
        WorkWeekColor: "#A52A2A",
        DayColor: "#B22222",
        MonthColor: "#CD5C5C"
    },

    // Immediate Family
    {
        Id: 77,
        Subject: "Father’s Birthday",
        StartTime: new Date(2025, 2, 20, 0, 0),
        EndTime: new Date(2025, 2, 20, 23, 59),
        Description: "Celebrating Father's special day",
        IsAllDay: true,
        IsReadOnly: true,
        CalendarId: 3,
        CategoryId: 14,
        EventType: "Birthday",
        WeekColor: "#FFD700",
        WorkWeekColor: "#FFA500",
        DayColor: "#FF8C00",
        MonthColor: "#DAA520"
    },
    {
        Id: 78,
        Subject: "Mother’s Birthday",
        StartTime: new Date(2025, 2, 11, 0, 0),
        EndTime: new Date(2025, 2, 11, 23, 59),
        Description: "Celebrating Mother's special day",
        IsAllDay: true,
        IsReadOnly: true,
        CalendarId: 3,
        CategoryId: 14,
        EventType: "Birthday",
        WeekColor: "#FF69B4",
        WorkWeekColor: "#FF1493",
        DayColor: "#C71585",
        MonthColor: "#DB7093"
    },
    {
        Id: 79,
        Subject: "Sister’s Birthday",
        StartTime: new Date(2025, 3, 10, 0, 0),
        EndTime: new Date(2025, 3, 10, 23, 59),
        Description: "Celebrating Sister’s birthday",
        IsAllDay: true,
        IsReadOnly: true,
        CalendarId: 3,
        CategoryId: 14,
        EventType: "Birthday",
        WeekColor: "#9370DB",
        WorkWeekColor: "#8A2BE2",
        DayColor: "#6A5ACD",
        MonthColor: "#7B68EE"
    },
    {
        Id: 80,
        Subject: "Brother’s Birthday",
        StartTime: new Date(2025, 11, 5, 0, 0),
        EndTime: new Date(2025, 11, 5, 23, 59),
        Description: "Celebrating Brother’s birthday",
        IsAllDay: true,
        IsReadOnly: true,
        CalendarId: 3,
        CategoryId: 14,
        EventType: "Birthday",
        WeekColor: "#1E90FF",
        WorkWeekColor: "#00BFFF",
        DayColor: "#87CEEB",
        MonthColor: "#4682B4"
    },
    {
        Id: 81,
        Subject: "Spouse’s Birthday",
        StartTime: new Date(2025, 2, 9, 0, 0),
        EndTime: new Date(2025, 2, 9, 23, 59),
        Description: "Celebrating Spouse’s birthday",
        IsAllDay: true,
        IsReadOnly: true,
        CalendarId: 3,
        CategoryId: 14,
        EventType: "Birthday",
        WeekColor: "#FF4500",
        WorkWeekColor: "#DC143C",
        DayColor: "#B22222",
        MonthColor: "#CD5C5C"
    },

    // Extended Family

    {
        Id: 82,
        Subject: "Grandfather’s Birthday",
        StartTime: new Date(2025, 1, 18, 0, 0),
        EndTime: new Date(2025, 1, 18, 23, 59),
        Description: "Celebrating Grandfather’s special day",
        IsAllDay: true,
        IsReadOnly: true,
        CalendarId: 3,
        CategoryId: 15,
        EventType: "Birthday",
        WeekColor: "#8B4513",
        WorkWeekColor: "#A0522D",
        DayColor: "#D2691E",
        MonthColor: "#CD853F"
    },
    {
        Id: 83,
        Subject: "Grandmother’s Birthday",
        StartTime: new Date(2025, 2, 13, 0, 0),
        EndTime: new Date(2025, 2, 13, 23, 59),
        Description: "Celebrating Grandmother’s special day",
        IsAllDay: true,
        IsReadOnly: true,
        CalendarId: 3,
        CategoryId: 15,
        EventType: "Birthday",
        WeekColor: "#DA70D6",
        WorkWeekColor: "#DDA0DD",
        DayColor: "#EE82EE",
        MonthColor: "#FFB6C1"
    },
    {
        Id: 84,
        Subject: "Father-in-law’s Birthday",
        StartTime: new Date(2025, 2, 15, 0, 0),
        EndTime: new Date(2025, 2, 15, 23, 59),
        Description: "Celebrating Father-in-law’s birthday",
        IsAllDay: true,
        IsReadOnly: true,
        CalendarId: 3,
        CategoryId: 15,
        EventType: "Birthday",
        WeekColor: "#708090",
        WorkWeekColor: "#778899",
        DayColor: "#2F4F4F",
        MonthColor: "#696969"
    },
    {
        Id: 85,
        Subject: "Mother-in-law’s Birthday",
        StartTime: new Date(2025, 9, 30, 0, 0),
        EndTime: new Date(2025, 9, 30, 23, 59),
        Description: "Celebrating Mother-in-law’s birthday",
        IsAllDay: true,
        IsReadOnly: true,
        CalendarId: 3,
        CategoryId: 15,
        EventType: "Birthday",
        WeekColor: "#FF6347",
        WorkWeekColor: "#FA8072",
        DayColor: "#FF7F50",
        MonthColor: "#FF4500"
    },

    // Friends & Close Circle

    {
        Id: 86,
        Subject: "Revanth’s Birthday",
        StartTime: new Date(2025, 2, 15, 0, 0),
        EndTime: new Date(2025, 2, 15, 23, 59),
        Description: "Celebrating Revanth’s birthday",
        IsAllDay: true,
        IsReadOnly: true,
        CalendarId: 3,
        CategoryId: 16,
        EventType: "Birthday",
        WeekColor: "#FF4500",
        WorkWeekColor: "#FF6347",
        DayColor: "#FF7F50",
        MonthColor: "#FA8072"
    },
    {
        Id: 87,
        Subject: "Rahul’s Birthday",
        StartTime: new Date(2025, 5, 10, 0, 0),
        EndTime: new Date(2025, 5, 10, 23, 59),
        Description: "Celebrating Rahul’s birthday",
        IsAllDay: true,
        IsReadOnly: true,
        CalendarId: 3,
        CategoryId: 16,
        EventType: "Birthday",
        WeekColor: "#20B2AA",
        WorkWeekColor: "#00CED1",
        DayColor: "#40E0D0",
        MonthColor: "#48D1CC"
    },
    {
        Id: 88,
        Subject: "Faith Leech’s Birthday",
        StartTime: new Date(2025, 8, 18, 0, 0),
        EndTime: new Date(2025, 8, 18, 23, 59),
        Description: "Celebrating Faith Leech’s birthday",
        IsAllDay: true,
        IsReadOnly: true,
        CalendarId: 3,
        CategoryId: 16,
        EventType: "Birthday",
        WeekColor: "#8A2BE2",
        WorkWeekColor: "#9370DB",
        DayColor: "#7B68EE",
        MonthColor: "#6A5ACD"
    },

    // Famous Personalities

    {
        Id: 89,
        Subject: "Ethel Anderson’s Birthday",
        StartTime: new Date(2025, 2, 15, 0, 0),
        EndTime: new Date(2025, 2, 15, 23, 59),
        Description: "Honoring Ethel Anderson’s birthday",
        IsAllDay: true,
        IsReadOnly: true,
        CalendarId: 3,
        CategoryId: 17,
        EventType: "Birthday",
        WeekColor: "#D2691E",
        WorkWeekColor: "#CD853F",
        DayColor: "#A0522D",
        MonthColor: "#8B4513"
    },
    {
        Id: 90,
        Subject: "Janet Rowley’s Birthday",
        StartTime: new Date(2025, 2, 12, 0, 0),
        EndTime: new Date(2025, 2, 12, 23, 59),
        Description: "Celebrating Janet Rowley’s birthday",
        IsAllDay: true,
        IsReadOnly: true,
        CalendarId: 3,
        CategoryId: 17,
        EventType: "Birthday",
        WeekColor: "#1E90FF",
        WorkWeekColor: "#4682B4",
        DayColor: "#5F9EA0",
        MonthColor: "#87CEEB"
    },
    {
        Id: 91,
        Subject: "Kasturba Gandhi’s Birthday",
        StartTime: new Date(2025, 4, 11, 0, 0),
        EndTime: new Date(2025, 4, 11, 23, 59),
        Description: "Honoring Kasturba Gandhi’s legacy",
        IsAllDay: true,
        IsReadOnly: true,
        CalendarId: 3,
        CategoryId: 17,
        EventType: "Birthday",
        WeekColor: "#FFD700",
        WorkWeekColor: "#FFA500",
        DayColor: "#FF8C00",
        MonthColor: "#DAA520"
    },
    {
        Id: 92,
        Subject: "Melissa Hayden’s Birthday",
        StartTime: new Date(2025, 5, 25, 0, 0),
        EndTime: new Date(2025, 5, 25, 23, 59),
        Description: "Celebrating Melissa Hayden’s birthday",
        IsAllDay: true,
        IsReadOnly: true,
        CalendarId: 3,
        CategoryId: 17,
        EventType: "Birthday",
        WeekColor: "#8A2BE2",
        WorkWeekColor: "#9370DB",
        DayColor: "#7B68EE",
        MonthColor: "#6A5ACD"
    },
    {
        Id: 93,
        Subject: "Mary Petty’s Birthday",
        StartTime: new Date(2025, 6, 29, 0, 0),
        EndTime: new Date(2025, 6, 29, 23, 59),
        Description: "Honoring Mary Petty’s birthday",
        IsAllDay: true,
        IsReadOnly: true,
        CalendarId: 3,
        CategoryId: 17,
        EventType: "Birthday",
        WeekColor: "#32CD32",
        WorkWeekColor: "#2E8B57",
        DayColor: "#3CB371",
        MonthColor: "#228B22"
    },
    {
        Id: 94,
        Subject: "Kay Petre’s Birthday",
        StartTime: new Date(2025, 8, 10, 0, 0),
        EndTime: new Date(2025, 8, 10, 23, 59),
        Description: "Celebrating Kay Petre’s birthday",
        IsAllDay: true,
        IsReadOnly: true,
        CalendarId: 3,
        CategoryId: 17,
        EventType: "Birthday",
        WeekColor: "#FF1493",
        WorkWeekColor: "#C71585",
        DayColor: "#DB7093",
        MonthColor: "#FF69B4"
    },
    {
        Id: 95,
        Subject: "Susanna Salter’s Birthday",
        StartTime: new Date(2025, 9, 2, 0, 0),
        EndTime: new Date(2025, 9, 2, 23, 59),
        Description: "Honoring Susanna Salter’s birthday",
        IsAllDay: true,
        IsReadOnly: true,
        CalendarId: 3,
        CategoryId: 17,
        EventType: "Birthday",
        WeekColor: "#DC143C",
        WorkWeekColor: "#B22222",
        DayColor: "#CD5C5C",
        MonthColor: "#8B0000"
    },
    {
        Id: 96,
        Subject: "Anne Bonny’s Birthday",
        StartTime: new Date(2025, 10, 8, 0, 0),
        EndTime: new Date(2025, 10, 8, 23, 59),
        Description: "Honoring Anne Bonny’s birthday",
        IsAllDay: true,
        IsReadOnly: true,
        CalendarId: 3,
        CategoryId: 17,
        EventType: "Birthday",
        WeekColor: "#000080",
        WorkWeekColor: "#191970",
        DayColor: "#4169E1",
        MonthColor: "#4682B4"
    },
];